# WHY USE NUMPY 

**TESTING THE SPEED OF PYTHON LIST AND NUMPY ARRAYS**

In [3]:
# using python list
import numpy as np
import time

size = 1_000_000

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x + y for x, y in zip(l1, l2)]
end = time.time()

print(add[0:10])
print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.23331642150878906


In [4]:
# using numpy arrays
import numpy as np
import time

size = 1_000_000

l1 = np.array(range(size))
l2 = np.array(range(size))

start = time.time()
add = l1+l2
end = time.time()

print(add[0:10])
print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.040814876556396484


**PYTHON ZIP EXPLAINED**

In [6]:
# python zip explained

l1=[1,2,3]
l2=[4,5,6]

zip(l1,l2) # gives zip object ie <zip at 0x1813fb3ad00>
list(zip(l1,l2)) # type-casting the zip object in list

[(1, 4), (2, 5), (3, 6)]

**NUMPY ARRAYS**

In [8]:
# 1D ARRAY

a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5 , "aparna"])

print(a)
print(b)
print(a.shape)
print(b.shape , "\n")
# 2D ARRAY

arr= np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))
print(arr.shape , "\n")

[1 2 3 4 5]
['1' '2' '3' '4' '5' 'aparna']
(5,)
(6,) 

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3) 



**MEMORY EFFICIENCY - NUMPY VS LIST**

In [10]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 4000 bytes


**VECTORIZATION - NO MORE LOOPS**

In [12]:
# PYTHON LIST - LOOP BASED
list1 = [1,2,3,4,5]
lst_sqr = [x ** 2 for x in list1]

# NUMPY - VECTORISED
arr1 = np.array([1,2,3,4,5])
numpy_sqr = arr1 ** 2

print(lst_sqr)
print(numpy_sqr)

[1, 4, 9, 16, 25]
[ 1  4  9 16 25]


**NUMPY IS FASTER THAN PYTHON LIST AS IT IS OPTIMISED IN C.**

**NUMPY CONSUMES LESS MEMORY**

**PROVIDES VECTORISED OPERATIONS**

---
---

# CREATING NUMPY ARRAYS

In [16]:
import numpy as np

# python list
lst = [1,2,3,4,5,6]
print(lst)

# numpy arrays
num_arr = np.array(lst)
print(num_arr)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [17]:
# 1 d array []
arr1 = np.array([1,2,3,4,5,33,7,35,14])
print(arr1 ,"\n")

# 2 d array --> data in rows n columns
arr2 = np.array([[1,2] , [3,6] , [3,5]])
print(arr2,"\n")

# multi-dimensional array --> matrix
mtx = np.array([[1,2,3] , [4,5,6]])
print(mtx)

[ 1  2  3  4  5 33  7 35 14] 

[[1 2]
 [3 6]
 [3 5]] 

[[1 2 3]
 [4 5 6]]


In [18]:
#  creating array from list
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [19]:
# array with default values --> np.zeros(size) or np.ones(size) or full(size , value)
zarr = np.zeros(3)
print(zarr ,"\n")

oarr = np.ones(4)
print(oarr ,"\n")
oarr2 = np.ones((2,3))
print(oarr2 ,"\n")

farr = np.full(2,8)
print(farr ,"\n")
farr2 = np.full((2,2),5)
print(farr2 ,"\n")

[0. 0. 0.] 

[1. 1. 1. 1.] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[8 8] 

[[5 5]
 [5 5]] 



In [20]:
# creating sequences of numbers in numpy --> arange(start , stop , step)
a = np.arange(1,100,4)
print(a)

[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]


In [21]:
# creating identity matrics --> .eye(size)
b = np.eye(4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
import numpy as np

arr=np.array([1,3,5]) #1d array
arr1=np.array([[1,2,3],[4,6,8]]) #2d array

print("1d array is :-",arr)
print("2d array is :-\n",arr1)

# array elements must have same data types

1d array is :- [1 3 5]
2d array is :-
 [[1 2 3]
 [4 6 8]]


In [23]:
np.zeros((3,4)) # 3x4 array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((3,5)) # 3x5 array of ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.full((4,6),8) # 4x6 array filled with 8

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [26]:
np.eye(4) # 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.arange(1,100,9) # (like range)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [28]:
np.linspace(1,100,5) # (evenly spaced)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [29]:
myarr = np.array([[10, 20, 30],[41, 53, 16], [40, 50, 60],[8,5,3]])
print("array is :- \n",myarr)
print("Shape:", myarr.shape)   # (x , y) → x rows, y columns
print("Size:", myarr.size)     #  → total elements
print("Dimensions:", myarr.ndim) # 2 → 2D array
print("Data type:", myarr.dtype) # int64 (or int32 on Windows)

myarr2 = np.array([[1,2,3] , [4,5,6] , [7,8,9]] , dtype = 'float32')
print("\n" , myarr2)

array is :- 
 [[10 20 30]
 [41 53 16]
 [40 50 60]
 [ 8  5  3]]
Shape: (4, 3)
Size: 12
Dimensions: 2
Data type: int32

 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [30]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

float32
[1 2 3]


In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

reshaped = arr.reshape((3, 2))  # Change shape
print("\n" , reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]

flattened = arr.flatten()  # Convert 2D → 1D
print("\n" ,flattened)  # [1 2 3 4 5 6]

(2, 3)

 [[1 2]
 [3 4]
 [5 6]]

 [1 2 3 4 5 6]


---

---

# INDEXING AND SLICING

In [33]:
import numpy as np
arr = np.array([[1,3,5],[7,4,8],[8,2,4]])
arr

array([[1, 3, 5],
       [7, 4, 8],
       [8, 2, 4]])

In [34]:
flat = arr.flatten() # making the arr -> 1D array

In [35]:
flat

array([1, 3, 5, 7, 4, 8, 8, 2, 4])

In [36]:
flat[0]

1

In [37]:
flat[1:6]

array([3, 5, 7, 4, 8])

In [38]:
flat[:5] # same as flat[0:5]

array([1, 3, 5, 7, 4])

In [39]:
flat[3:] # same as flat[3 : 10]

array([7, 4, 8, 8, 2, 4])

In [40]:
# Indexing (Same as Python Lists)
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


In [41]:
# Slicing (Extracting Parts of an Array) 

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30]


In [42]:
# Slicing returns a view, not a copy! 
# Changes affect the original array.
sliced = arr[1:4]
sliced[0] = 999
print(arr)  # [10 999 30 40 50]

[ 10 999  30  40]


In [43]:
# making copy of an array
print("original array is :- ",arr)
slice= arr[0:5].copy()
print("slice array is :- ",slice)
slice[0]=200
print("slice array after change :- ",slice)
print("original array after change :- ",arr)

original array is :-  [ 10 999  30  40]
slice array is :-  [ 10 999  30  40]
slice array after change :-  [200 999  30  40]
original array after change :-  [ 10 999  30  40]


In [44]:
# Fancy Indexing & Boolean Masking

# Fancy Indexing (Select Multiple Elements)
arr = np.array([10,32,54,87,8,79,70,20,32,5,75,50])
idx = [0,2,4,6,8,9,10]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 54  8 70 32  5 75]


In [45]:
# Boolean Masking (Filter Data)

arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]


---

---

# MULTI DIMENSIONAL INDEXING AND AXIS

In [47]:
# Example: Axes in a 2D Array

import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print(arr)

# Understanding Axes in NumPy

# 1D array → 1 axis (axis 0)
# 2D array → 2 axes (axis 0 = rows, axis 1 = columns)
# 3D array → 3 axes (axis 0 = depth, axis 1 = rows, axis 2 = columns)

# Axis 0 (rows) → Operations move down the columns.
# Axis 1 (columns) → Operations move across the rows.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
print(np.sum(arr, axis=0))  # Sum along rows (down each column)
print(np.sum(arr, axis=1))  # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [49]:
# Indexing in Multidimensional Arrays

print(arr[1, 2])  # Row index 1, Column index 2
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

#  Indexing in 3D Arrays
# For 3D arrays, the first index refers to the "depth" (sheets of data).
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]]) # array of 2D arrays
 
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

6
[[2 3]
 [5 6]]
(2, 2, 3)


In [50]:
# Accessing elements in 3D:

# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6
 
print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [51]:
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[1 4 7]
[[1 2 3]
 [7 8 9]]


In [52]:
# Changing Data Along an Axis
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]


In [53]:
arr3D2 = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
arr3D2[: , 0 , :] = 0
print(arr3D2)

[[[ 0  0  0]
  [ 4  5  6]]

 [[ 0  0  0]
  [10 11 12]]]


---

---

# DATA TYPES IN NUMPY

In [107]:
# Common Data Types in NumPy:
# int32, int64: Integer types with different bit sizes.
# float32, float64: Floating-point types with different precision.
# bool: Boolean data type.
# complex64, complex128: Complex number types.
# object: For storing objects (e.g., Python objects, strings).

# FOR CHECKING THE DATA TYPE OF A VARIABLE --> dtype
# CONVERTING ONE TYPE TO ANOTHER --> astype(np.datatype)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int64 (or int32 depending on the system)

int32


In [99]:
# Example: Changing Data Types
arr = np.array([1.5, 2.7, 3.9])
print(arr.dtype)  # Output: float64
 
arr_int = arr.astype(np.int32)  # Converting float to int
print(arr_int)    # Output: [1 2 3]
print(arr_int.dtype)  # Output: int32

# Example: Downcasting to Save Memory
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32)  # Downcasting to a smaller dtype
print(arr_small)  # Output: [1000000 2000000 3000000]
print(arr_small.dtype)  # Output: int32

# Example: Memory Usage
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
 
print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

# Example: String Array
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10')  # Unicode string array
print(arr)

# Example: Complex Numbers
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)

# Example: Object Data Type
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

float64
[1 2 3]
int32
[1000000 2000000 3000000]
int32
24
12
['apple' 'banana' 'cherry']
[1.+2.j 3.+4.j 5.+6.j]
[{'a': 1} list([1, 2, 3]) 'hello']


---

---

# BROADCASTING & VECTORISATION

In [114]:
# Example: Looping Over Arrays in Python

import numpy as np
 
arr = np.array([1, 2, 3, 4, 5])
result = []
 
# Using a loop to square each element (slow)
for num in arr:
    result.append(num ** 2)
 
print(result)  # Output: [1, 4, 9, 16, 25]

[1, 4, 9, 16, 25]


In [116]:
# Example: Vectorized Operation
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2  # Vectorized operation
print(result)  # Output: [1 4 9 16 25]

[ 1  4  9 16 25]


In [119]:
# Example: Broadcasting with Scalar

arr = np.array([1, 2, 3, 4, 5])
result = arr + 10  # Broadcasting: 10 is added to all elements
print(result)  # Output: [11 12 13 14 15]

[11 12 13 14 15]


In [121]:
# Example: Broadcasting with Two Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])
 
result = arr1 + arr2  # Element-wise addition
print(result)  # Output: [11 22 33]

[11 22 33]


In [123]:
# Example: Broadcasting a 2D Array and a 1D Array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
 
result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)
# Output:
# [[2 4 6]
#  [5 7 9]]

[[2 4 6]
 [5 7 9]]


In [125]:
# Example: Normalizing Data Using Broadcasting

# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])
 
# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)
 
# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
 
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


---

---

# MATHEMATICAL FUNCTIONS

In [129]:
import numpy as np
arr=np.array([1,3,5,2,7,5])

# np.mean() – Compute the mean (average) of an array.

np.mean(arr)

3.8333333333333335

In [131]:
# np.std() – Compute the standard deviation of an array.

np.std(arr)

2.034425935955617

In [133]:
# np.var() – Compute the variance of an array.

np.var(arr)

4.138888888888888

In [135]:
# np.min() – Compute the minimum value of an array.

np.min(arr)

1

In [137]:
# np.max() – Compute the maximum value of an array.

np.max(arr)

7

In [139]:
# np.sum() – Compute the sum of all elements in an array.

np.sum(arr)

23

In [141]:
# np.prod() – Compute the product of all elements in an array.

np.prod(arr)

1050

In [143]:
# np.median() – Compute the median of an array.

np.median(arr)

4.0

In [145]:
# np.percentile() – Compute the percentile of an array.

np.percentile(arr, 50)  # For the 50th percentile (median)

4.0

In [147]:
# np.argmin() – Return the index of the minimum value in an array.

np.argmin(arr)

0

In [149]:
# np.argmax() – Return the index of the maximum value in an array.

np.argmax(arr)

4

In [151]:
# np.unique() – Find the unique elements of an array.

np.unique(arr)

array([1, 2, 3, 5, 7])

In [153]:
# np.diff() – Compute the n-th differences of an array.

np.diff(arr)

array([ 2,  2, -3,  5, -2])

In [155]:
# np.cumsum() – Compute the cumulative sum of an array.

np.cumsum(arr)

array([ 1,  4,  9, 11, 18, 23])

In [157]:
# np.linspace() – Create an array with evenly spaced numbers over a specified interval.

np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [159]:
# np.log() – Compute the natural logarithm of an array.

np.log(arr)

array([0.        , 1.09861229, 1.60943791, 0.69314718, 1.94591015,
       1.60943791])

In [161]:
# np.exp() – Compute the exponential of an array.

np.exp(arr)

array([   2.71828183,   20.08553692,  148.4131591 ,    7.3890561 ,
       1096.63315843,  148.4131591 ])

In [163]:
# np.corrcoef() – Compute the correlation coefficient matrix of two arrays.
arr1= np.array([1,3,5,7])
arr2=np.array([2,5,4,10])
np.corrcoef(arr1, arr2)

array([[1.        , 0.87243973],
       [0.87243973, 1.        ]])

---

---