# INTRODUCTION OF NUMPY ARRAYS AND PYTHON LIST

In [102]:
import numpy as np

# Introduction to Python lists and numpy arrays 
py_lst = [1,2,3,4,5]
print(py_lst)

print("\n")

num_arr = np.array([1,2,3,4,5])
print(num_arr)

[1, 2, 3, 4, 5]


[1 2 3 4 5]


In [103]:
# 1,2,multi-dimensional(matrix) arrays in numpy 
arr_1d = np.array([12,20,54,67])
print(arr_1d)

print("\n")

arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr_2d)

print("\n")

multi_arr = np.array([[1,2],
                      [2,4]])
print(multi_arr)

[12 20 54 67]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2]
 [2 4]]


In [104]:
# creating numpy arrays with default values

# .zeros(shape)
zero_arr = np.zeros(3)
print(zero_arr)

print("\n")

# .ones(shape)
one_arr = np.ones((2,3))
print(one_arr)

print("\n")

# .full(shape , value)
full_arr = np.full((3,3),4)
print(full_arr)

[0. 0. 0.]


[[1. 1. 1.]
 [1. 1. 1.]]


[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [105]:
# creating sequences of numbers in numpy 

# arange(start , stop , step)
seq = np.arange(1,10,2)
print(seq)

print("\n")

# creating identity matrix
# eye(size)
iden_matrix = np.eye(3)
print(iden_matrix)

[1 3 5 7 9]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [106]:
# using python list[]
temp = [32.5 , 51.2 , 32.6 , 36.1]
total = 0
for t in temp :
    total += t
avg = total/len(temp)
print(avg)

print("\n")

# using numpy arrays
temps = np.array([32.5 , 51.2 , 32.6 , 36.1])
avg2 = np.mean(temps)
print(avg2)

38.1


38.1


# NUMPY ARRAY PROPERTIES AND OPERATIONS

In [108]:
# shape of an numpy array
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr_2d.shape)

(3, 3)


In [109]:
# size of an numpy array --> gives total no. of elements 
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr_2d.size)

9


In [110]:
# ndim --> no. of dimensions
arr_2d = np.array([[1,2,3],
                  [4,5,6]])
print(arr_2d.ndim)

2


In [111]:
# .dtype --> check the data type of elements
arr = np.array([1.2,3.4,4.5])
print(arr.dtype)

float64


In [112]:
# .astype(newdatatype) --> change the data type
arr = np.array([1.2,3.4,4.5])
int_arr = arr.astype(int)
print(arr)
print(int_arr)

[1.2 3.4 4.5]
[1 3 4]


In [113]:
# maths operations
arr = np.array([10,20,30,40])

print(arr+5)
print(arr**2)
print(arr*2)

[15 25 35 45]
[ 100  400  900 1600]
[20 40 60 80]


In [114]:
# aggregation function

# np.sum(array) --> add all elements
# np.mean(array) --> calculate average
# np.min(array) --> min element
# np.max(array) --> max element
# np.std(array) --> standard deviation
# np.var(array) --> variance

arr = np.array([10,20,30,40])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

100
25.0
10
40
11.180339887498949
125.0


# INDEXING & SLICING

In [116]:
# array[index] --> 1D array
# array[row , column] --> 2D array

arr = np.array([10,20,30,40])
print(arr[0]) # first element
print(arr[2])
print(arr[-1]) #last element

10
30
40


In [117]:
# extracting sub-array
# slicing -> array[start , stop-1 , step]
# array[start , end] --> start to end-1
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[1:5])
print(arr[:4])
print(arr[::2])
print(arr[::-1]) #reversing an array

[20 30 40 50]
[10 20 30 40]
[10 30 50 70 90]
[90 80 70 60 50 40 30 20 10]


In [118]:
# fancy indexing --> selecting multiple elements at once
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr[[0,2,4]])

# boolean masking --> filtering data based on a condition
print(arr[arr>25])

[10 30 50]
[30 40 50 60 70 80 90]


# RESHAPING AND MANIPULATION

In [120]:
# reshaping --> changing dimension/shape of data without modifying it 
# reshaping --> does not create a copy but creates a view 
# arr.reshape(rows, columns) 
# --> specify new shape, can only do this if dimensions match
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr.reshape(5,2))
print(arr.reshape(2,5))

[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [121]:
# flattering array --> convert multi-dimensional array to 1D array
# two functions --> .ravel() [returns a view] 
#               --> .flatten() [creates a copy]
arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr2.ravel())
print(arr2.flatten())

[10 20 30 40 50 60 70 80 90]
[10 20 30 40 50 60 70 80 90]


# ARRAY MODIFICATION

In [123]:
# ADVANCE NUMPY
# np.insert(array , index , value , axis = None)
# axis = 0 [row-wise] [by default] , = 1 [column wise]

# insert in 1D array
arr = np.array([10,20,40,50,60,70])
print(arr)
new_arr = np.insert(arr , 2 , 30)
print(new_arr , "\n")

# insert in 2D array
arr2 = np.array([[10,20],[40,50]])
print(arr2)
new_arr2 = np.insert(arr2 , 2 , [50,60] , axis = 0)
# new_arr2 = np.insert(arr2 , 2 , [50,60] , axis = None) 
# --> ans : [10 20 50 60 40 50] --> adds element in straight line
print(new_arr2)

[10 20 40 50 60 70]
[10 20 30 40 50 60 70] 

[[10 20]
 [40 50]]
[[10 20]
 [40 50]
 [50 60]]


In [124]:
# append --> np.array(array , elements) --> add element at the end
arr = np.array([10 ,20 ,50 ,60 ,40])
new_arr = np.append(arr , [30 , 70])
print(new_arr)

[10 20 50 60 40 30 70]


In [125]:
# concatenate --> join two or more arrays
# np.concatenate((arr1 , arr2) , axis = 0)
# axis --> 0 - vertical stacking , --> 1 - horizontal stacking
arr1 = np.array([10 , 20 , 50]) 
arr2 = np.array([60 , 40 , 30])
new_arr = np.concatenate((arr1 , arr2))
print(new_arr)

[10 20 50 60 40 30]


In [126]:
# removing elements of an array
# np.delete(array , index , axis = None)
# axis = None --> deleting from 1D array

# 1D array
arr = np.array([10 ,20 ,50 ,60 ,40 ,50])
print(arr)
new_arr = np.delete(arr , 2)
print(new_arr , "\n")

# 2D array
arr2 = np.array([[10 , 20 , 50] , [60 , 40 , 50]])
new_arr2 = np.delete(arr2 , 0 , axis = 0)
print(arr2)
print(new_arr2)

[10 20 50 60 40 50]
[10 20 60 40 50] 

[[10 20 50]
 [60 40 50]]
[[60 40 50]]


In [127]:
# stacking --> combining arrays
# two types --> vertically or horizontally
# vstack() --> row wise , hstack --> column wise
arr1 = np.array([1 , 2 , 3])
arr2 = np.array([4 , 5 , 6])
print(np.vstack((arr1 , arr2)) , "\n")
print(np.hstack((arr1 , arr2)))

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6]


In [128]:
# splitting --> dividing an array into subparts
# np.split(array , no. of parts) --> equally split  
# np.hsplit() --> horizontally split  
# np.vsplit() --> verstucally split

arr1 = np.array([1 , 2 , 3 , 4 , 5 , 6])
print(np.split(arr1 , 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


# BROADCASTING AND VECTORISATION

In [151]:
# BROADCASTING

# using for loop

prices = [100, 200, 300]
discount  = 10
final_prices = []
for price in prices :
    final_price = price - (price * discount/100)
    final_prices.append(final_price)
print(final_prices)

# using broadcasting

prices = np.array([100 , 200 , 300])
discount = 10
final_price = prices - (prices * discount / 100)
print(final_price)

[90.0, 180.0, 270.0]
[ 90. 180. 270.]


In [149]:
# how numpy handles arrays of different shapes
# 1. matching dimensions
# 2. expanding single elements
# 3. incompatible shapes

arr = np.array([100 , 200 , 300])
result = arr * 2
print(result,"\n")

matrix = np.array([[1,2,3] , [4,5,6]]) # 2 x 3 matrix
vector = np.array([10 , 20 , 30])
result = matrix + vector
print(result)

arr1 = np.array([[1,2,3] , [4,5,6]]) #shape(2,3)
arr2 = np.array([1,2]) #shape(2)
# result = arr1 + arr2 --> gives error
# print(result) --> gives error
# we can use --> .reshape()

[200 400 600] 

[[11 22 33]
 [14 25 36]]


In [161]:
# VECTORIZATION

# USING LIST COMPREHENSIONS
lst1 = [1,2,3]
lst2 = [4,5,6]
result = [x+y for x,y in zip(lst1 , lst2)]
print(result)

# fast vector method
lst3 = np.array([1,2,3])
lst4 = np.array([4,5,6])
result = lst3 + lst4
print(result)

arrv = np.array([10,20,30])
mult = arr * 3
print(mult)

# broadcasting --> expand smaller arrays to larger arrays
#              --> faster than loops

# vectorization --> operation on whole array
#               --> 100 times faster than loops


[5, 7, 9]
[5 7 9]
[300 600 900]


# HANDLING MISSING VALUES

In [167]:
# np.isnan --> handles missing values
# nan --> not a number

arr = np.array([1 , 2 , np.nan , 4 , np.nan , 6])
print(np.isnan(arr))

# we cannot compare like this 
# print(np.nan == np.nan)

[False False  True False  True False]


In [171]:
# nan_to_num(array , nan = value) --> replace nan value with any number 
# [default is 0]
arr = np.array([1 , 2 , np.nan , 4 , np.nan , 6])
ans = np.nan_to_num(arr , nan = 10)
print(ans)

[ 1.  2. 10.  4. 10.  6.]


In [175]:
# np.isinf(array) --> check whether any value is infinite
arr = np.array([1 , 2 , 3 , np.inf , 4 , -np.inf])
print(np.isinf(arr))

[False False False  True False  True]


In [181]:
# replacing infinite values
arr = np.array([1 , 2 , 3 , np.inf , 4 , -np.inf])
ans = np.nan_to_num(arr , posinf = 1000 , neginf = -1000)
print(ans)

[    1.     2.     3.  1000.     4. -1000.]


# CAPSTONE PROJECT